apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TejiriH/multi-cluster-app  # Replace with your repo URL
    targetRevision: main
    path: overlays/prod   # Use the Kustomize dev environment
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
